// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonOJxJXrZ2AYZUf5KEO3-SnnbepZixz0',
    appId: '1:729215777178:web:8fbbe3ec6efd4c41096223',
    messagingSenderId: '729215777178',
    projectId: 'fir-firebase-setup-f815f',
    authDomain: 'fir-firebase-setup-f815f.firebaseapp.com',
    storageBucket: 'fir-firebase-setup-f815f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgwwe40R_pzo4WB9PGv7F1OpsHZ8Rmj0',
    appId: '1:729215777178:android:79878646b4838df7096223',
    messagingSenderId: '729215777178',
    projectId: 'fir-firebase-setup-f815f',
    storageBucket: 'fir-firebase-setup-f815f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5_t5Eifhdg42mUeyoGNlVpR5C0i6kAc',
    appId: '1:729215777178:ios:66e9a55338650dbb096223',
    messagingSenderId: '729215777178',
    projectId: 'fir-firebase-setup-f815f',
    storageBucket: 'fir-firebase-setup-f815f.firebasestorage.app',
    iosBundleId: 'com.example.timelog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5_t5Eifhdg42mUeyoGNlVpR5C0i6kAc',
    appId: '1:729215777178:ios:66e9a55338650dbb096223',
    messagingSenderId: '729215777178',
    projectId: 'fir-firebase-setup-f815f',
    storageBucket: 'fir-firebase-setup-f815f.firebasestorage.app',
    iosBundleId: 'com.example.timelog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBonOJxJXrZ2AYZUf5KEO3-SnnbepZixz0',
    appId: '1:729215777178:web:c119623f007371c9096223',
    messagingSenderId: '729215777178',
    projectId: 'fir-firebase-setup-f815f',
    authDomain: 'fir-firebase-setup-f815f.firebaseapp.com',
    storageBucket: 'fir-firebase-setup-f815f.firebasestorage.app',
  );
}
